# Exercise 2.03

In this exercise we are going to perform some matrix multiplication.

## Matrix Multiplication

In linear algebra, when multiplying two matrices, the number of *columns* of the first matrix must
equal the number of *rows* in the second matrix. The inner dimensions must match.

- It is **_valid_** to multiply a `3x4` matrix by a `4x3` matrix. (`3x4`) $\times$ (`4x3`) - The inner dimesion, 4, matches.
- It is **_invalid_** to multiply a `3x4` matrix by a `3x4` matrix. (`3x4`) $\times$ (`3x4`) - The inner dimesion, 4 and 3, does not match.

The resulting matrix will have the same number of rows as the first matrix and the same number of columns as the second matrix. Or the outer dimensions of the multiplication.

Let's recreate 2 matrices of the same size to work with

In [1]:
import numpy as np
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
mat1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [2]:
mat2 = np.array([[2, 1, 4], [4, 1, 7], [4, 2, 9], [5, 21, 1]])
mat2

array([[ 2,  1,  4],
       [ 4,  1,  7],
       [ 4,  2,  9],
       [ 5, 21,  1]])

We can take a looks at the shape of the matrices

In [3]:
mat1.shape

(4, 3)

In [4]:
mat2.shape

(4, 3)

These matrices won't multiply because the inner dimensions do not match -- (`4x3`) $\times$ (`4x3`)

In order for these to multiply correctly we can either reshape or transpose one of the matrices such that the inner dimensions match.

If we transpose the second matrix in the product we will have (`4x3`) $\times$ (`4x3`)$^T$ = (`4x3`) $\times$ (`3x4`)
The resulting matrix will be (`4x4`).

Let's try that.

In [5]:
mat1.dot(mat2.T)

array([[ 16,  27,  35,  50],
       [ 37,  63,  80, 131],
       [ 58,  99, 125, 212],
       [ 79, 135, 170, 293]])

If we transpose the first matrix in the product we will have (`4x3`)$^T$ $\times$ (`4x3`) = (`3x4`) $\times$ (`4x3`)
The resulting matrix will be (`3x3`).

Let's try that.

In [6]:
mat1.T.dot(mat2)

array([[ 96, 229, 105],
       [111, 254, 126],
       [126, 279, 147]])

We can also reshape one of the matrices so that the inner dimensions of the matrix product match.

In [7]:
np.reshape(mat1, [3,4]).dot(mat2)

array([[ 42,  93,  49],
       [102, 193, 133],
       [162, 293, 217]])

This worked, producing a (`3x3`) matrix.