# Exercise 4

## Tensor Multiplication
In this exercise we are going to demonstrate how to perform matrix multiplication on tensors that both have at least 3 dimensions.

Let's start with creating a tensor with 3 dimensions

In [1]:
import numpy as np
mat1 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
mat1

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

Let's verify that the shape has 3 dimensions

In [2]:
mat1.shape

(2, 2, 3)

Great, it has 3 dimensions.

Now we need another matrix that has at least one dimension that matches in size. We can do this by taking the transpose of the matrix.

In [3]:
mat2 = mat1.T
mat2

array([[[1, 1],
        [4, 4]],

       [[2, 2],
        [5, 5]],

       [[3, 3],
        [6, 6]]])

Let's look at the shape

In [4]:
mat2.shape

(3, 2, 2)

Now we have our two matrices we can mutiply them in a number of different ways, we just have to make sure the inner dimensions match. If we multiply with `mat2` first then we expect our resultant matrix to be:

$$
mat2_{3\times2\times2}\times mat1_{2\times2\times3} = mat3_{3\times2\times2\times3}
$$

We end up with a 4-dimensional tensor.

In [5]:
mat3 = mat2.dot(mat1)
mat3

array([[[[ 5,  7,  9],
         [ 5,  7,  9]],

        [[20, 28, 36],
         [20, 28, 36]]],


       [[[10, 14, 18],
         [10, 14, 18]],

        [[25, 35, 45],
         [25, 35, 45]]],


       [[[15, 21, 27],
         [15, 21, 27]],

        [[30, 42, 54],
         [30, 42, 54]]]])

And let's verify the shape

In [6]:
mat3.shape

(3, 2, 2, 3)