# Exercise 2.02

In this exercise we are going to perform some matrix reshaping and transposition.

## Array Reshaping
One way to change the dimensions of an array is to reshape it, which is different than transposing. A matrix can be reshaped if the number of elements in the resulting array or matrix is the same as the original array.

For example we can change the shape of our matrix from a (`4x3`) to a (`3x4`), or a (`6x2`), or a (`1x12`), or even a (`3x2x2`), because they all have 12 total values in each.

In [1]:
import numpy as np
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
mat1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

We can take a look at the shape of this array

In [2]:
mat1.shape

(4, 3)

This matrix has 4 rows and 3 columns.

We can reshape the array to have 3 rows and 4 columns using the `reshape` function

In [3]:
mat2 = np.reshape(mat1, [3,4])
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

We can confirm by looking at the shape of the matrix

In [4]:
mat2.shape

(3, 4)

Reshaping can even change the rank, or number of dimensions. For example we can create a 3-dimensional matrix.

In [5]:
mat3 = np.reshape(mat1, [3,2,2])
mat3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

And we can confirm by looking at the shape

In [6]:
mat3.shape

(3, 2, 2)

We can even convert to a 1-dimensional array if we please

In [7]:
mat4 = np.reshape(mat1, [12])
mat4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
mat4.shape

(12,)

Reshaping can be a useful way to get matrices of the correct shape for multiplication. Some human interpretability may be sacrificed in the process but reversing the reshaping can always be applied.

## Transposition

Vector transposition converts a row vector to a column vector and vice versa.

When a matrix is transposed, the matrix gets flipped over its diagonal, as such the number of rows and columns are interchanged.

A superscript $^\text{T}$ is used for transposed matrices.

$$
A=
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}
$$

$$
A^{\text{T}}=
\begin{bmatrix}
    A_{1,1} & A_{2,1} & A_{3,1} \\\\
    A_{1,2} & A_{2,2} & A_{3,2}
\end{bmatrix}
$$

Here, ($3 \times 2$), A, has become a ($2 \times 3$). The shape ($m \times n$) is inverted and becomes ($n \times m$).

The method to transpose arrays and matrices in numpy is the `T` method and can be used as follows:

In [9]:
mat = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
mat

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [10]:
mat.T

matrix([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])

We can check the dimensions of the matrices:

In [11]:
mat.shape

(4, 3)

In [12]:
mat.T.shape

(3, 4)

We can see that the number of columns becomes the number of rows with transposition and vice versa.

Transposing and reshaping result in different matrices.

We can confirm this by looking cell by cell which are the same.

In [13]:
np.reshape(mat1, [3,4]) == mat1.T

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

Only very first and very last element are equivalent