# Exercise 2.01

## Scalars, Vectors, Matrices and Tensors

Let's start with some basic definitions:

<em>Difference between a scalar, a vector, a matrix and a tensor</em>

- A scalar is a single number
- A vector is a one-dimensional array of numbers
- A matrix is a two-dimensional array of numbers
- A tensor is a $n$-dimensional array of numbers with $n>2$


We will start by creating a vector. This is just a 1-dimensional array of numbers, we can use the numpy library since it includes many functions for working with and processing vectors and matrices.

In [1]:
import numpy as np
vec1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
vec1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can also create matrices with the same `array` function, here we can pass an array of arrays.

In [2]:
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
mat1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Another way we can create a matrix is by using the `matrix` function. We provide the function the same array of arrays to initialize the matrix.

In [3]:
mat2 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
mat2

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

The difference between creating matrices with the two format are the methods that the `array` and `matrix` class have.

We can also create 3-dimensional array, or tensor, by passing an array of arrays of arrays to the `array` function.

In [4]:
ten1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
ten1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Shape

The shape of an vector or matrix is determined by the number of values in the vector or matrix in each dimension. For a vector the shape is determined by the total number of elements in the vector, since it is 1-dimensional. For a matrix it will give you the number of rows and columns in the matrix (in general the rows are provided first).

We can determine the shape of our vectors and matrices as follows:

In [5]:
vec1.shape

(10,)

The value is simply 10.

And for the matrices:

In [6]:
mat1.shape

(4, 3)

We can see the matrix has 4 rows and 3 columns.

Finally, for tensors:

In [7]:
ten1.shape

(2, 2, 3)

Note that we can also use the `len()` function to determine the first element of the `shape` method. For vectors this is equivalent to the shape, and for matrices this is equivalent to the number of rows.

## Addition

Matrices can be added if they have the same shape.
This is achieved by adding the corresponding cell from each matrix together. The resulting matric will have the same shape as the two input matrices.

$$A_{i,j} + B_{i,j} = C_{i,j}$$

$i$ is the row index and $j$ the column index.

$$
C=
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,2} \\\\
    B_{2,1} & B_{2,2} \\\\
    B_{3,1} & B_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,2} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,2} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,2}
\end{bmatrix}
$$


With Numpy you can add matrices just as you would add vectors or scalars.

In [8]:
mat1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
mat1

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [9]:
mat2 = np.matrix([[2, 1, 4], [4, 1, 7], [4, 2, 9], [5, 21, 1]])
mat2

matrix([[ 2,  1,  4],
        [ 4,  1,  7],
        [ 4,  2,  9],
        [ 5, 21,  1]])

In [10]:
# Add matrices mat1 and mat2
mat3 = mat1 + mat2
mat3

matrix([[ 3,  3,  7],
        [ 8,  6, 13],
        [11, 10, 18],
        [15, 32, 13]])

Scalar values can also be added to matrices. This is achieved by adding the scalar value to each cell of the matrix.

$$
\alpha+ \begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    \alpha + A_{1,1} & \alpha + A_{1,2} \\\\
    \alpha + A_{2,1} & \alpha + A_{2,2} \\\\
    \alpha + A_{3,1} & \alpha + A_{3,2}
\end{bmatrix}
$$

In [11]:
mat1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
mat1

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [12]:
mat1 + 4

matrix([[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13],
        [14, 15, 16]])